### PR TITLE
Add network speed tokens

### PR DESCRIPTION
**Pull request by patrick96**
%downspeed% and %upspeed%

### CODE REVIEW

**Comment by patrick96** [comment]
Hold on with merging, I'm getting an `std::out_of_range` because the number of bytes in `rx_bytes` or `tx_bytes` is bigger than the max size of `int`
Fix will be up later this evening

**Comment by patrick96** [comment]
Is there a reason that this is not getting merged or are you just too busy?

**Comment by jaagr** [comment]
Hi, I have rewritten large parts of the application so I've been waiting with new stuff until that's released. Hoping to get it out shortly.

**Comment by patrick96** [comment]
Alright, no problem!

**Comment by jaagr** [comment]
Closing this, partially added to 2.0

**Pull request closed without merging**
