### PR TITLE
feat(temperature): Added temp module and examples

### PR DESCRIPTION
**Pull request by NBonaparte**
Adds temperature module. A specific thermal zone `thermal-zone` can be set, and a threshold temperature `temperature-warn` can be specified for displaying a separate 'warning' label `label-warn`.

### CODE REVIEW

**Comment by jaagr** [comment]
Nice.. could you also add a page to the wiki on how to configure the module?

**Comment by NBonaparte** [comment]
Unfortunately, I don't have write access to the wiki.

**Comment by jaagr** [comment]
There, now the wiki should be writable by everyone now..

**Comment by NBonaparte** [comment]
Thanks! I've added a page for the temperature module and also a volume mapping example from dce81d4266d970e36d0b1c382bcbf28b3e1c865a.

**Comment by jaagr** [comment]
Great! I've added support for `<ramp>` to the module, to allow icons based on temp value. Will add it to the wiki as well.

**Pull request merged**
